<?php $mensagem = $_SESSION['mensagem'] ?? ''; $tipo = $_SESSION['tipo_mensagem'] ?? 'success'; unset($_SESSION['mensagem'], $_SESSION['tipo_mensagem']); ?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Alunos | Lista</title><link rel="stylesheet" href="assets/style.css"></head><body>
<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-icon">A</div><span>Alunos+</span></div><div class="nav-title">Menu</div><nav class="nav"><a class="active" href="index.php?pagina=alunos">▦ <span>Alunos</span></a><a href="index.php?pagina=dashboard">⌂ <span>Dashboard</span></a></nav></aside>
<main class="main"><div class="topbar"><div><h1>Alunos</h1><div class="muted">Gerencie os estudantes cadastrados.</div></div><div class="user"><div class="avatar"><?= strtoupper(substr($_SESSION['usuario_nome'],0,1)) ?></div><div><?= htmlspecialchars($_SESSION['usuario_nome']) ?></div></div></div>
<?php if($mensagem): ?><div class="notice <?= $tipo === 'error' ? 'error' : 'success' ?>"><?= htmlspecialchars($mensagem) ?></div><?php endif; ?>
<div class="card"><div class="card-head"><h2>Lista de alunos</h2><a class="btn" href="index.php?pagina=novo">+ Novo aluno</a></div>
<div class="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Idade</th><th>Curso</th><th>Status</th><th>Ações</th></tr></thead><tbody>
<?php if(!$alunos): ?><tr><td colspan="6" class="empty">Nenhum aluno cadastrado. Clique em “Novo aluno” para começar.</td></tr><?php endif; ?>
<?php foreach($alunos as $aluno): ?><tr><td><strong><?= htmlspecialchars($aluno['nome']) ?></strong></td><td><?= htmlspecialchars($aluno['email']) ?></td><td><?= (int)$aluno['idade'] ?></td><td><?= htmlspecialchars($aluno['curso']) ?></td><td><span class="badge">Ativo</span></td><td><div class="actions"><a class="btn secondary" href="index.php?pagina=editar&id=<?= (int)$aluno['id'] ?>">Editar</a><form method="POST" action="index.php" onsubmit="return confirm('Excluir este aluno?')"><input type="hidden" name="acao" value="excluir_aluno"><input type="hidden" name="id" value="<?= (int)$aluno['id'] ?>"><button class="btn danger" type="submit">Excluir</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div></div></main></div></body></html>
